// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfCgYXzoDTDGdrkWLdVjGsdDEBudIumw',
    appId: '1:1088730968345:web:cc6fcb1166fd47bb0fd588',
    messagingSenderId: '1088730968345',
    projectId: 'insura-seguros',
    authDomain: 'insura-seguros.firebaseapp.com',
    storageBucket: 'insura-seguros.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19Unj3ybdiSsXXXXi_CCSeXsucjqBu1c',
    appId: '1:1088730968345:android:5dae981d4afde8420fd588',
    messagingSenderId: '1088730968345',
    projectId: 'insura-seguros',
    storageBucket: 'insura-seguros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcB4_7J3iC2a9CcFrAGdOyAgOHxbVBAqw',
    appId: '1:1088730968345:ios:d8b3ced53d9849f10fd588',
    messagingSenderId: '1088730968345',
    projectId: 'insura-seguros',
    storageBucket: 'insura-seguros.firebasestorage.app',
    iosBundleId: 'com.example.insura',
  );
}
